name: dism
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.5.1
  google_sign_in: ^4.0.2
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  material_design_icons_flutter: ^3.2.3595
  snowm_scanner: ^0.8.0+4

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
